### ISSUE TITLE
Also support mime type application/vnd.ms-tnef

### ISSUE THREAD

**Issue by janhoy** [jukka/jtnef#1]
In src/net/freeutils/tnef/tika/TNEFParser.java, also support application/vnd.ms-tnef which is the official mime type for TNEF

**Comment by jukka** [comment]
Done in commit 4efd2f3e748f27c3cfbae2d3197c7d7a2f5439ff.

**Comment by janhoy** [comment]
Since both mime types are in use, shouldn't we return a collection of both, for the parser to kick in for either mimetype? The mimetypes.xml in Tika now lists both mime types, one an alias of the other.

**Comment by jukka** [comment]
Tika will automatically normalize the media type to the official one before looking up which parser to use, so there's no need to list the alias.

**Comment by janhoy** [comment]
That makes sense. Thanks.
